import { useEffect, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import Nav from "components/Nav";
import SubmitForm from "components/SubmitForm";
import SkillsCarousel from "components/SkillsCarousel";
import { EMPLOYMENT_HISTORY, NAME_FINAL } from "../constants";

const Home: NextPage = () => {
  const [name, setName] = useState("");

  useEffect(() => {
    for (let i = 0; i <= NAME_FINAL.length; i++) {
      // Slices string from 0 to current iteration
      const nameSlice = NAME_FINAL.slice(0, i);

      setTimeout(function () {
        setName(nameSlice);
      }, i * 80);
    }
  }, []);

  return (
    <>
      <Head>
        {/* <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />*/}

        <title>Gustavo Maurício - Developer</title>
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Nav />

      <main className="main-contender">
        <section
          id="home"
          className="home-section text-white flex items-center h-screen md:h-[70vh]"
        >
          <div className="container px-4 mx-auto">
            <div className="flex justify-center gap-7 flex-col md:flex-row">
              <div className="flex justify-center py-2 w-full sm:w-1/4 sm:justify-end">
                <Image
                  className="avatar"
                  height={140}
                  width={140}
                  src="/img/gustavo.png"
                  alt="avatar"
                />
              </div>
              <div className="flex items-center py-2 w-full sm:w-3/4">
                <div className="tracking-widest">
                  <h3 className="uppercase text-3xl mb-2" id="name">
                    {name}
                  </h3>
                  <h5 className="uppercase text-xl">Software Engineer</h5>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="py-24" id="overview">
          <div className="container px-4 mx-auto">
            <div>
              <h5 className="tracking-widest uppercase text-center text-xl">
                Overview
              </h5>
              <hr />
              <p className="text-center mb-4">
                Personal development is my main goal. I'm constantly reading,
                improving my skills and learning something new every day.
              </p>
              <p className="text-center">
                From a young age I've always been fascinated by computers and
                how things worked behind the scenes. I'm also a passionate
                problem solver, math lover and logical person. Those qualities
                and traits together made me follow this developer path.
              </p>
            </div>
          </div>
        </section>
        <section className="py-24 bg-gray-200" id="skills">
          <div className="container px-4 mx-auto">
            <div className="flex">
              <div className="col">
                <h5 className="tracking-widest uppercase text-center text-xl">
                  Skills
                </h5>
                <hr />
                <p className="text-center">
                  I have a strong preference and want to expertise in front-end
                  development but I've always been kinda full stack and I think
                  it's important to understand an entire application end to end.
                  I've worked mostly with AngularJS and React on the client
                  side, node and .net server side and also have some experience
                  with SQL in general.
                </p>
                <SkillsCarousel />
              </div>
            </div>
          </div>
        </section>
        <section className="py-24" id="employment">
          <div className="container px-4 mx-auto">
            <div className="w-full">
              <h5 className="tracking-widest uppercase text-center text-xl">
                Employment
              </h5>
              <hr />
              <p className="text-center mb-4">
                Apart from jobs I always tend to be working on some side
                projects, it's due to those that I've learned some technologies
                like react and node. I don't normaly do open source, mainly
                because most of the projects I've done have some kind of
                commercial purpose. I have a strong preference for a remote
                position, they let me manage my time way more efficiently, I end
                up being more productive and it's also easier to keep track and
                maintain some of those side projects, it just fits my lifestyle
                better.
              </p>
              {EMPLOYMENT_HISTORY.map((entry) => (
                <div className="py-4" key={entry.company}>
                  <div className="flex justify-between mb-2">
                    <h6 className="uppercase">{entry.company}</h6>
                    <h6>{entry.date}</h6>
                  </div>
                  <p>{entry.role}</p>
                  <hr className="opacity-20 max-w-full" />
                </div>
              ))}
            </div>
          </div>
        </section>
        <section className="py-24 bg-gray-200" id="contact">
          <div className="container px-4 mx-auto">
            <div className="w-full mb-3">
              <h5 className="tracking-widest uppercase text-center text-xl">
                Contact
              </h5>
              <hr className="mb-10" />
              <SubmitForm />
            </div>
            <div className="w-full flex justify-center pb-3">
              <a
                href="https://www.linkedin.com/in/gustavo-mauricio/"
                target="_blank"
                rel="noopener noreferrer"
              >
                <i className="fab fa-2x fa-linkedin color mx-2"></i>
              </a>
              <a
                href="https://twitter.com/gustavomwy"
                target="_blank"
                rel="noopener noreferrer"
              >
                <i className="fab fa-2x fa-twitter color mx-2"></i>
              </a>
            </div>
          </div>
        </section>
      </main>

      <footer className="py-2 bg-black text-white text-center">
        &#169; Made by <span className="color-primary">Gustavo Mauricio</span>
      </footer>
    </>
  );
};

export default Home;
